"""change column name for artist'

Revision ID: 07b55d3c080c
Revises: bdc553dd1db2
Create Date: 2024-07-05 12:09:53.987874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b55d3c080c'
down_revision = 'bdc553dd1db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=500), nullable=True))
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('website')

    # ### end Alembic commands ###
