"""adding venue field

Revision ID: 3a0da3fdbe96
Revises: 8501641d432c
Create Date: 2024-07-01 14:03:25.774874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0da3fdbe96'
down_revision = '8501641d432c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_seeking_talent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seeking_talent_message', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('seeking_talent_message')
        batch_op.drop_column('is_seeking_talent')
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
