"""adding new FK

Revision ID: 93ad07ceb2a9
Revises: ababe1a405b4
Create Date: 2024-07-01 15:47:57.173560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ad07ceb2a9'
down_revision = 'ababe1a405b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'])
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
