"""adding new field for Artist and init Show model

Revision ID: ababe1a405b4
Revises: 3a0da3fdbe96
Create Date: 2024-07-01 14:10:05.220113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ababe1a405b4'
down_revision = '3a0da3fdbe96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_seeking_venue', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seeking_venue_message', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('seeking_venue_message')
        batch_op.drop_column('is_seeking_venue')
        batch_op.drop_column('website_link')

    op.drop_table('Show')
    # ### end Alembic commands ###
